#' Save Graph to PDF
#'
#' Saves a graphical object (e.g., a plot) to a PDF file at the specified path. This function is useful for exporting generated plots to PDF format for reports, presentations, or further analysis.
#' @param grph The graphical object to save. Typically, this would be an object generated by plotting functions in R, such as those from `ggplot2` or base R plotting functions.
#' @param path The path where the PDF file should be saved, excluding the file extension. The '.pdf' extension is automatically appended to this path in the function.
#' @param width Optional. The width of the PDF document in inches. Default is 10.
#' @param height Optional. The height of the PDF document in inches. Default is 8.
#' @return Invisibly returns NULL. The function's primary effect is the side-effect of creating a PDF file at the specified location containing the graphical representation of the `grph` object.
#' @examples
#' # Assuming `plot_obj` is a plot object created using ggplot2 or base R plotting
#' Savegrph(plot_obj, "path/to/save/your_plot")
#' @export

Savegrph <- function(grph, path, width = 10, height = 8){
  # 1. Open jpeg file
  pdf(paste(path, ".pdf", sep = ""), width = width, height = height)
  # 2. Create the plot
  print(grph)
  # 3. Close the file
  dev.off()
}
